[versions]
lib = "1.0.0"
agp = "8.13.0"
korlibs-crypto = "6.0.1"
kotlin = "2.2.21"
publish = "0.34.0"
versions = "0.53.0"

[libraries]
korlibs-crypto = { group = "com.soywiz", name = "korlibs-crypto", version.ref = "korlibs-crypto" }

[plugins]
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }